with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

footer_start = 55942
footer_end = 61061

new_footer = (
    '<!-- Pre-Footer CTA Band -->\n'
    '    <div class="footer-cta-strip">\n'
    '        <div class="footer-cta-left reveal">\n'
    '            <span class="footer-cta-eyebrow">Get In Touch</span>\n'
    '            <div class="footer-cta-headline">\n'
    '                Ready to upgrade<br>your <em>clinical arsenal?</em>\n'
    '            </div>\n'
    '        </div>\n'
    '        <a href="#" class="footer-cta-btn">\n'
    '            Talk to a Specialist\n'
    '            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="18" height="18"><path d="M7 17L17 7M17 7H7M17 7v10"/></svg>\n'
    '        </a>\n'
    '    </div>\n\n'
    '    <!-- Main Footer -->\n'
    '    <footer class="footer-premium">\n\n'
    '        <div class="footer-main">\n'
    '            <div class="footer-grid">\n\n'
    '                <!-- Brand -->\n'
    '                <div class="footer-col reveal" style="transition-delay:0.05s">\n'
    '                    <span class="footer-logo">MEDICO<span>.</span></span>\n'
    '                    <span class="footer-tagline">Caring &middot; Respirating</span>\n'
    '                    <p class="footer-desc">Kashmir&rsquo;s most trusted partner for clinical-grade respiratory and life-support equipment. Serving hospitals, clinics &amp; families since 2000.</p>\n'
    '                </div>\n\n'
    '                <!-- Navigate -->\n'
    '                <div class="footer-col reveal" style="transition-delay:0.1s">\n'
    '                    <h4>Navigate</h4>\n'
    '                    <ul class="footer-links">\n'
    '                        <li><a href="#">Home</a></li>\n'
    '                        <li><a href="#catalogue-grid">Products</a></li>\n'
    '                        <li><a href="#about-us">About Us</a></li>\n'
    '                        <li><a href="#">Contact</a></li>\n'
    '                        <li><a href="#">Admin Login</a></li>\n'
    '                    </ul>\n'
    '                </div>\n\n'
    '                <!-- Explore -->\n'
    '                <div class="footer-col reveal" style="transition-delay:0.2s">\n'
    '                    <h4>Explore</h4>\n'
    '                    <ul class="footer-links">\n'
    '                        <li><a href="#">Blogs</a></li>\n'
    '                        <li><a href="#">Certifications</a></li>\n'
    '                        <li><a href="#">Reviews</a></li>\n'
    '                        <li><a href="#">Clinician Login</a></li>\n'
    '                    </ul>\n'
    '                </div>\n\n'
    '                <!-- Connect -->\n'
    '                <div class="footer-col reveal" style="transition-delay:0.3s">\n'
    '                    <h4>Connect</h4>\n'
    '                    <div class="social-icons">\n'
    '                        <a href="#" class="social-icon" aria-label="Facebook">\n'
    '                            <svg viewBox="0 0 24 24"><path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"/></svg>\n'
    '                        </a>\n'
    '                        <a href="#" class="social-icon" aria-label="YouTube">\n'
    '                            <svg viewBox="0 0 24 24"><path d="M22.54 6.42a2.78 2.78 0 00-1.95-1.96C18.88 4 12 4 12 4s-6.88 0-8.59.46A2.78 2.78 0 001.46 6.42 29 29 0 001 12a29 29 0 00.46 5.58 2.78 2.78 0 001.95 1.96C5.12 20 12 20 12 20s6.88 0 8.59-.46a2.78 2.78 0 001.95-1.96A29 29 0 0023 12a29 29 0 00-.46-5.58zM9.75 15.02V8.98L15.5 12l-5.75 3.02z"/></svg>\n'
    '                        </a>\n'
    '                        <a href="#" class="social-icon" aria-label="LinkedIn">\n'
    '                            <svg viewBox="0 0 24 24"><path d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"/><circle cx="4" cy="4" r="2"/></svg>\n'
    '                        </a>\n'
    '                        <a href="#" class="social-icon" aria-label="Instagram">\n'
    '                            <svg viewBox="0 0 24 24"><rect x="2" y="2" width="20" height="20" rx="5" ry="5" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="4" fill="currentColor"/><circle cx="17.5" cy="6.5" r="1.5" fill="currentColor"/></svg>\n'
    '                        </a>\n'
    '                        <a href="#" class="social-icon" aria-label="WhatsApp">\n'
    '                            <svg viewBox="0 0 24 24"><path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"/></svg>\n'
    '                        </a>\n'
    '                    </div>\n'
    '                    <div class="footer-accent-line"></div>\n'
    '                    <div class="footer-contact-text">\n'
    '                        <a href="mailto:medicosgr@gmail.com">medicosgr@gmail.com</a>\n'
    '                        <a href="tel:+919419008453">+91 94190 08453</a>\n'
    '                    </div>\n'
    '                </div>\n\n'
    '            </div>\n'
    '        </div>\n\n'
    '        <div class="footer-bottom">\n'
    '            <span class="footer-bottom-left">&copy; 2026 Medico Scientific Service Centre. All rights reserved.</span>\n'
    '            <div class="footer-bottom-right">\n'
    '                <a href="#">Privacy Policy</a>\n'
    '                <a href="#">Terms of Use</a>\n'
    '                <a href="#">Sitemap</a>\n'
    '            </div>\n'
    '        </div>\n\n'
    '    </footer>'
)

new_content = content[:footer_start] + new_footer + content[footer_end:]

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(new_content)

print('Done. Size:', len(new_content))
